### ISSUE TITLE
sign should take a file path

### ISSUE THREAD

**Issue by mixmix** [entropyxyz/cli#304]

**Comment by rh0delta** [comment]
I am more inclined to use the -f option rather than creating a whole new command for signing a file. We can also update sign to be similar to how git works with commit messages where -m allows us to write a quick and easy string message

**Comment by mixmix** [comment]
I like the `-f` as well

## Tasks

- [ ] 1. Write example code
    - [ ] the `-f` case
    - [ ] the string input case
- [ ] 2. Write up the test cases
    - if we are allowing string or file, then defend against both
    - if you sign a string in a file it must behave same as signing the string?
- [ ] 3. **Research** (2) above, leaving notes in this issue:
    - make sure the "file read + sign" works same as "string + sign"
    - this may be blocking on the "verify" method from SDK 🙈  (cc @frankiebee)

Once these are done, change status back to "Up Next", "blocked" "Needs Research"

**Comment by frankiebee** [comment]
moving to `blocked` till we have the verify function fleshed out 
see #79
