### ISSUE TITLE
Add a `Verify` demo to verify an entropy signature from a file

### ISSUE THREAD

**Issue by tuxxy** [entropyxyz/cli#79]
After you execute the `Sign` demo, you should be able to `Verify` the signature in a similar demo.

**Comment by mixmix** [comment]
## Tasks

1. [ ] get verify function into SDK 
2. [ ] create `/src/verify/main.ts`
  -  test it
3. [ ] design CLI input/ ouput
  - examples
  - get it reviewed
5. [ ] design TUI input/ output
  - examples
  - get it reviewed
6. [ ] implement
